# populate_verbs.py
from app import create_app
from models import db, Verb

app = create_app()

with app.app_context():
    verbs = [
        {"norwegian": "å angripe", "english_meanings": "to attack", "past": "angrep", "past_participle": "angrepet", "mnemonic": "Sounds like 'attack'."},
        {"norwegian": "å anholde", "english_meanings": "to arrest", "past": "anholdt", "past_participle": "anholdt", "mnemonic": "Think 'arrest hold'."},
        {"norwegian": "å ankomme", "english_meanings": "to arrive", "past": "ankom", "past_participle": "ankommet", "mnemonic": "Arrived on time."},
        {"norwegian": "å anse", "english_meanings": "to consider", "past": "anså", "past_participle": "ansett", "mnemonic": "Consider carefully."},
        {"norwegian": "å ansette", "english_meanings": "to hire", "past": "ansatte", "past_participle": "ansatt", "mnemonic": "Hire someone for a job."},
        {"norwegian": "å anta", "english_meanings": "to assume", "past": "antok", "past_participle": "antatt", "mnemonic": "Assume as true."},
        {"norwegian": "å avbryte", "english_meanings": "to interrupt", "past": "avbrøt", "past_participle": "avbrutt", "mnemonic": "Interrupt the conversation."},
        {"norwegian": "å avgi", "english_meanings": "to emit / give off", "past": "avgav", "past_participle": "avgitt", "mnemonic": "Emit light or sound."},
        {"norwegian": "å avgjøre", "english_meanings": "to decide / determine", "past": "avgjorde", "past_participle": "avgjort", "mnemonic": "Make a decision."},
        {"norwegian": "å avholde", "english_meanings": "to hold (a meeting)", "past": "avholdt", "past_participle": "avholdt", "mnemonic": "Hold a session."},
        {"norwegian": "å avstå", "english_meanings": "to abstain", "past": "avstod", "past_participle": "avstått", "mnemonic": "Refrain from something."},
        {"norwegian": "å avta", "english_meanings": "to decrease", "past": "avtok", "past_participle": "avtatt", "mnemonic": "Decrease gradually."},
        {"norwegian": "å avvike", "english_meanings": "to deviate", "past": "avvek", "past_participle": "avveket", "mnemonic": "Stray from the norm."},
        {"norwegian": "å be", "english_meanings": "to ask / pray", "past": "ba", "past_participle": "bedt", "mnemonic": "Ask politely."},
        {"norwegian": "å begi", "english_meanings": "to undertake", "past": "begav", "past_participle": "begitt", "mnemonic": "Undertake an action."},
        {"norwegian": "å bestå", "english_meanings": "to pass / consist of", "past": "besto", "past_participle": "bestått", "mnemonic": "Pass an exam."},
        {"norwegian": "å bidra", "english_meanings": "to contribute", "past": "bidro", "past_participle": "bidratt", "mnemonic": "Contribute to a cause."},
        {"norwegian": "å bifalle", "english_meanings": "to approve", "past": "bifalt", "past_participle": "bifalt", "mnemonic": "Approve of something."},
        {"norwegian": "å binde", "english_meanings": "to bind", "past": "bandt", "past_participle": "bundet", "mnemonic": "Bind tightly."},
        {"norwegian": "å bistå", "english_meanings": "to assist", "past": "bistod", "past_participle": "bistått", "mnemonic": "Offer assistance."},
        {"norwegian": "å bite", "english_meanings": "to bite", "past": "bet", "past_participle": "bitt", "mnemonic": "Bite with teeth."},
        {"norwegian": "å bli", "english_meanings": "to become", "past": "ble", "past_participle": "blitt", "mnemonic": "Transform into something new."},
        {"norwegian": "å bosette", "english_meanings": "to settle", "past": "bosatte", "past_participle": "bosatt", "mnemonic": "Settle in a place."},
        {"norwegian": "å brekke", "english_meanings": "to break (fracture)", "past": "brakk", "past_participle": "brukket", "mnemonic": "Break suddenly."},
        {"norwegian": "å brenne", "english_meanings": "to burn", "past": "brant", "past_participle": "brent", "mnemonic": "Burn intensely."},
        {"norwegian": "å bringe", "english_meanings": "to bring", "past": "brakte", "past_participle": "brakt", "mnemonic": "Bring something along."},
        {"norwegian": "å bryte", "english_meanings": "to break", "past": "brøt", "past_participle": "brutt", "mnemonic": "Break apart."},
        {"norwegian": "å burde", "english_meanings": "should / ought to", "past": "burdet", "past_participle": "burdet", "mnemonic": "Express obligation."},
        {"norwegian": "å by", "english_meanings": "to bid / offer", "past": "bydde", "past_participle": "bydd", "mnemonic": "Place a bid."},
        {"norwegian": "å bære", "english_meanings": "to carry", "past": "bar", "past_participle": "båret", "mnemonic": "Carry with effort."},
        {"norwegian": "å delta", "english_meanings": "to participate", "past": "deltok", "past_participle": "deltatt", "mnemonic": "Join the activity."},
        {"norwegian": "å dra", "english_meanings": "to go / leave", "past": "dro", "past_participle": "dratt", "mnemonic": "Depart quickly."},
        {"norwegian": "å drikke", "english_meanings": "to drink", "past": "drakk", "past_participle": "drukket", "mnemonic": "Drink up."},
        {"norwegian": "å drive", "english_meanings": "to drive / operate", "past": "drev", "past_participle": "drevet", "mnemonic": "Drive a vehicle."},
        {"norwegian": "å dø", "english_meanings": "to die", "past": "døde", "past_participle": "dødd", "mnemonic": "Pass away."},
        {"norwegian": "å ete", "english_meanings": "to eat", "past": "åt", "past_participle": "ett", "mnemonic": "Have a meal."},
        {"norwegian": "å etterkomme", "english_meanings": "to comply", "past": "etterkom", "past_participle": "etterkommet", "mnemonic": "Follow orders."},
        {"norwegian": "å etterlate", "english_meanings": "to leave behind", "past": "etterlot", "past_participle": "etterlatt", "mnemonic": "Leave a legacy."},
        {"norwegian": "å falle", "english_meanings": "to fall", "past": "falt", "past_participle": "falt", "mnemonic": "Fall down."},
        {"norwegian": "å fastslå", "english_meanings": "to determine / establish", "past": "fastslo", "past_participle": "fastslått", "mnemonic": "Establish a fact."},
        {"norwegian": "å ferdes", "english_meanings": "to travel", "past": "ferdes", "past_participle": "ferdes", "mnemonic": "Travel around."},
        {"norwegian": "å finne", "english_meanings": "to find", "past": "fant", "past_participle": "funnet", "mnemonic": "Discover something."},
        {"norwegian": "å finnes", "english_meanings": "to exist", "past": "fantes", "past_participle": "funnet", "mnemonic": "Simply exist."},
        {"norwegian": "å fly", "english_meanings": "to fly", "past": "fløy", "past_participle": "flydd", "mnemonic": "Soar in the sky."},
        {"norwegian": "å flyte", "english_meanings": "to float", "past": "fløt", "past_participle": "flytt", "mnemonic": "Drift on water."},
        {"norwegian": "å forbryte", "english_meanings": "to commit a crime", "past": "forbrøt", "past_participle": "forbrutt", "mnemonic": "Commit an offense."},
        {"norwegian": "å forby", "english_meanings": "to forbid", "past": "forbød", "past_participle": "forbudt", "mnemonic": "Not allowed."},
        {"norwegian": "å fordra", "english_meanings": "to detest / abhor", "past": "fordrog", "past_participle": "fordratt", "mnemonic": "Abhor strongly."},
        {"norwegian": "å foregå", "english_meanings": "to occur", "past": "foregikk", "past_participle": "foregått", "mnemonic": "Happen as events."},
        {"norwegian": "å foreslå", "english_meanings": "to propose", "past": "foreslo", "past_participle": "foreslått", "mnemonic": "Suggest an idea."},
        {"norwegian": "å foretrekke", "english_meanings": "to prefer", "past": "foretrakk", "past_participle": "foretrukket", "mnemonic": "Favor one option."},
        {"norwegian": "å forfølge", "english_meanings": "to pursue", "past": "forfulgte", "past_participle": "forfulgt", "mnemonic": "Chase after."},
        {"norwegian": "å forgå", "english_meanings": "to perish", "past": "forgikk", "past_participle": "forgått", "mnemonic": "Pass away gradually."},
        {"norwegian": "å forholde", "english_meanings": "to relate / behave", "past": "forholdt", "past_participle": "forholdt", "mnemonic": "Act in a certain way."},
        {"norwegian": "å forlate", "english_meanings": "to leave", "past": "forlot", "past_participle": "forlatt", "mnemonic": "Depart from a place."},
        {"norwegian": "å forstå", "english_meanings": "to understand", "past": "forsto", "past_participle": "forstått", "mnemonic": "Comprehend clearly."},
        {"norwegian": "å forsvinne", "english_meanings": "to vanish", "past": "forsvant", "past_participle": "forsvunnet", "mnemonic": "Disappear suddenly."},
        {"norwegian": "å fortelle", "english_meanings": "to tell", "past": "fortalte", "past_participle": "fortalt", "mnemonic": "Narrate a story."},
        {"norwegian": "å fortsette", "english_meanings": "to continue", "past": "fortsatte", "past_participle": "fortsatt", "mnemonic": "Keep going."},
        {"norwegian": "å forutsette", "english_meanings": "to assume", "past": "forutsatte", "past_participle": "forutsatt", "mnemonic": "Presume beforehand."},
        {"norwegian": "å frambringe", "english_meanings": "to produce", "past": "frambrakte", "past_participle": "frambrakt", "mnemonic": "Bring forth something."},
        {"norwegian": "å frita", "english_meanings": "to excuse / exonerate", "past": "fritok", "past_participle": "fritatt", "mnemonic": "Excuse from duty."},
        {"norwegian": "å fryse", "english_meanings": "to freeze", "past": "frøs", "past_participle": "frosset", "mnemonic": "Turn to ice."},
        {"norwegian": "å få", "english_meanings": "to get / receive", "past": "fikk", "past_participle": "fått", "mnemonic": "Obtain something."},
        {"norwegian": "å følge", "english_meanings": "to follow", "past": "fulgte", "past_participle": "fulgt", "mnemonic": "Follow in footsteps."},
        {"norwegian": "å gi", "english_meanings": "to give", "past": "gav", "past_participle": "gitt", "mnemonic": "Offer generously."},
        {"norwegian": "å gidde", "english_meanings": "to bother", "past": "gadd", "past_participle": "giddet", "mnemonic": "Lack the energy to care."},
        {"norwegian": "å gjelde", "english_meanings": "to apply / concern", "past": "gjaldt", "past_participle": "gjeldt", "mnemonic": "Apply to all."},
        {"norwegian": "å gjennomgå", "english_meanings": "to undergo / review", "past": "gjennomgikk", "past_participle": "gjennomgått", "mnemonic": "Experience a process."},
        {"norwegian": "å gjenta", "english_meanings": "to repeat", "past": "gjentok", "past_participle": "gjentatt", "mnemonic": "Do it again."},
        {"norwegian": "å gjenvinne", "english_meanings": "to regain", "past": "gjenvant", "past_participle": "gjenvunnet", "mnemonic": "Win back possession."},
        {"norwegian": "å gjøre", "english_meanings": "to do", "past": "gjorde", "past_participle": "gjort", "mnemonic": "Perform an action."},
        {"norwegian": "å gli", "english_meanings": "to slip", "past": "gled", "past_participle": "glidd", "mnemonic": "Slide away."},
        {"norwegian": "å gni", "english_meanings": "to rub", "past": "gnidde", "past_participle": "gnidd", "mnemonic": "Rub gently."},
        {"norwegian": "å godta", "english_meanings": "to accept", "past": "godtok", "past_participle": "godtatt", "mnemonic": "Accept without hesitation."},
        {"norwegian": "å gravlegge", "english_meanings": "to bury", "past": "gravla", "past_participle": "gravlagt", "mnemonic": "Lay to rest."},
        {"norwegian": "å gripe", "english_meanings": "to seize", "past": "grep", "past_participle": "grepet", "mnemonic": "Grab quickly."},
        {"norwegian": "å grunnlegge", "english_meanings": "to establish", "past": "grunnla", "past_participle": "grunnlagt", "mnemonic": "Lay a foundation."},
        {"norwegian": "å gråte", "english_meanings": "to cry", "past": "gråt", "past_participle": "grått", "mnemonic": "Let the tears flow."},
        {"norwegian": "å gå", "english_meanings": "to go", "past": "gikk", "past_participle": "gått", "mnemonic": "Move along."},
        {"norwegian": "å ha", "english_meanings": "to have", "past": "hadde", "past_participle": "hatt", "mnemonic": "Possess something."},
        {"norwegian": "å henge", "english_meanings": "to hang", "past": "hang", "past_participle": "hengt", "mnemonic": "Suspend from above."},
        {"norwegian": "å hete", "english_meanings": "to be called", "past": "heta", "past_participle": "hetet", "mnemonic": "Be given a name."},
        {"norwegian": "å hjelpe", "english_meanings": "to help", "past": "hjalp", "past_participle": "hjulpet", "mnemonic": "Offer assistance."},
        {"norwegian": "å holde", "english_meanings": "to hold", "past": "holdt", "past_participle": "holdt", "mnemonic": "Grasp firmly."},
        {"norwegian": "å høres", "english_meanings": "to be heard", "past": "hørtes", "past_participle": "hørt", "mnemonic": "Sound is perceived."},
        {"norwegian": "å innebære", "english_meanings": "to entail", "past": "innebar", "past_participle": "innebåret", "mnemonic": "Imply a consequence."},
        {"norwegian": "å inneha", "english_meanings": "to possess", "past": "innehadde", "past_participle": "innehatt", "mnemonic": "Hold ownership."},
        {"norwegian": "å inneholde", "english_meanings": "to contain", "past": "inneholdt", "past_participle": "inneholdt", "mnemonic": "Enclose within."},
        {"norwegian": "å inngå", "english_meanings": "to enter into", "past": "inngikk", "past_participle": "inngått", "mnemonic": "Enter an agreement."},
        {"norwegian": "å innse", "english_meanings": "to realize", "past": "innså", "past_participle": "innsett", "mnemonic": "Comprehend suddenly."},
        {"norwegian": "å innsette", "english_meanings": "to insert / install", "past": "innsatte", "past_participle": "innsatt", "mnemonic": "Place in position."},
        {"norwegian": "å inntre", "english_meanings": "to enter", "past": "inntrådte", "past_participle": "inntrådt", "mnemonic": "Step inside."},
        {"norwegian": "å inntreffe", "english_meanings": "to occur", "past": "inntraff", "past_participle": "inntreffet", "mnemonic": "Happen unexpectedly."},
        {"norwegian": "å iscenesette", "english_meanings": "to stage", "past": "iscenesatte", "past_participle": "iscenesatt", "mnemonic": "Put on a performance."},
        {"norwegian": "å ivareta", "english_meanings": "to safeguard", "past": "ivaretok", "past_participle": "ivaretatt", "mnemonic": "Take care of."},
        {"norwegian": "å kartlegge", "english_meanings": "to map out", "past": "kartla", "past_participle": "kartlagt", "mnemonic": "Chart the details."},
        {"norwegian": "å klype", "english_meanings": "to pinch", "past": "klypte", "past_participle": "klypt", "mnemonic": "Squeeze lightly."},
        {"norwegian": "å knekke", "english_meanings": "to crack", "past": "knakk", "past_participle": "knekket", "mnemonic": "Break open."},
        {"norwegian": "å komme", "english_meanings": "to come", "past": "kom", "past_participle": "kommet", "mnemonic": "Arrive at a place."},
        {"norwegian": "å krype", "english_meanings": "to crawl", "past": "krøyp", "past_participle": "krøpet", "mnemonic": "Crawl slowly."},
        {"norwegian": "å kunne", "english_meanings": "to be able to", "past": "kunne", "past_participle": "kunnet", "mnemonic": "Have the ability."},
        {"norwegian": "å la", "english_meanings": "to let", "past": "lot", "past_participle": "latt", "mnemonic": "Allow to happen."},
        {"norwegian": "å late", "english_meanings": "to pretend", "past": "lot", "past_participle": "latt", "mnemonic": "Feign an emotion."},
        {"norwegian": "å le", "english_meanings": "to laugh", "past": "lo", "past_participle": "ledd", "mnemonic": "Laugh out loud."},
        {"norwegian": "å legge", "english_meanings": "to put / lay", "past": "la", "past_participle": "lagt", "mnemonic": "Place something down."},
        {"norwegian": "å lete", "english_meanings": "to search", "past": "lette", "past_participle": "lett", "mnemonic": "Look for something."},
        {"norwegian": "å lide", "english_meanings": "to suffer", "past": "led", "past_participle": "lidd", "mnemonic": "Endure hardship."},
        {"norwegian": "å ligge", "english_meanings": "to lie (recline)", "past": "lå", "past_participle": "ligget", "mnemonic": "Rest in bed."},
        {"norwegian": "å lyde", "english_meanings": "to sound", "past": "lydde", "past_participle": "lydt", "mnemonic": "Produce a sound."},
        {"norwegian": "å lyge", "english_meanings": "to lie (deceive)", "past": "løy", "past_participle": "løyet", "mnemonic": "Speak falsely."},
        {"norwegian": "å lykkes", "english_meanings": "to succeed", "past": "lyktes", "past_participle": "lyktes", "mnemonic": "Achieve your goal."},
        {"norwegian": "å lyve", "english_meanings": "to lie (deceit)", "past": "løy", "past_participle": "løyet", "mnemonic": "Tell an untruth."},
        {"norwegian": "å løpe", "english_meanings": "to run", "past": "løp", "past_participle": "løpt", "mnemonic": "Run swiftly."},
        {"norwegian": "å løslate", "english_meanings": "to release", "past": "løslot", "past_participle": "løslatt", "mnemonic": "Let go of restraint."},
        {"norwegian": "å minnes", "english_meanings": "to remember", "past": "mintes", "past_participle": "mintes", "mnemonic": "Keep in mind."},
        {"norwegian": "å misforstå", "english_meanings": "to misunderstand", "past": "misforsto", "past_participle": "misforstått", "mnemonic": "Get it wrong."},
        {"norwegian": "å motta", "english_meanings": "to receive", "past": "mottok", "past_participle": "mottatt", "mnemonic": "Accept what is given."},
        {"norwegian": "å måtte", "english_meanings": "to have to", "past": "måtte", "past_participle": "måttet", "mnemonic": "Need to do something."},
        {"norwegian": "å møtes", "english_meanings": "to meet", "past": "møttes", "past_participle": "møttes", "mnemonic": "Come together."},
        {"norwegian": "å nedlegge", "english_meanings": "to abolish", "past": "nedla", "past_participle": "nedlagt", "mnemonic": "Put an end to something."},
        {"norwegian": "å nedsette", "english_meanings": "to dismiss", "past": "nedsatte", "past_participle": "nedsatt", "mnemonic": "Lower the status."},
        {"norwegian": "å nyse", "english_meanings": "to sneeze", "past": "nyste", "past_participle": "nyst", "mnemonic": "Expel air suddenly."},
        {"norwegian": "å nyte", "english_meanings": "to enjoy", "past": "nøt", "past_participle": "nytt", "mnemonic": "Savor the moment."},
        {"norwegian": "å omgå", "english_meanings": "to bypass / circumvent", "past": "omgikk", "past_participle": "omgått", "mnemonic": "Go around obstacles."},
        {"norwegian": "å omgås", "english_meanings": "to socialize", "past": "omgikkes", "past_participle": "omgåttes", "mnemonic": "Spend time with others."},
        {"norwegian": "å oppdra", "english_meanings": "to bring up / educate", "past": "oppdro", "past_participle": "oppdratt", "mnemonic": "Raise a child."},
        {"norwegian": "å oppfinne", "english_meanings": "to invent", "past": "oppfant", "past_participle": "oppfunnet", "mnemonic": "Create something new."},
        {"norwegian": "å oppgi", "english_meanings": "to give up", "past": "oppgav", "past_participle": "oppgitt", "mnemonic": "Surrender reluctantly."},
        {"norwegian": "å oppholde", "english_meanings": "to stay / reside", "past": "oppholdt", "past_participle": "oppholdt", "mnemonic": "Remain somewhere."},
        {"norwegian": "å opprettholde", "english_meanings": "to maintain", "past": "opprettholdt", "past_participle": "opprettholdt", "mnemonic": "Keep things in order."},
        {"norwegian": "å oppstå", "english_meanings": "to arise", "past": "oppsto", "past_participle": "oppstått", "mnemonic": "Emerge unexpectedly."},
        {"norwegian": "å oppta", "english_meanings": "to occupy", "past": "opptok", "past_participle": "opptatt", "mnemonic": "Take up space."},
        {"norwegian": "å opptre", "english_meanings": "to perform", "past": "opptrådte", "past_participle": "opptrådt", "mnemonic": "Take the stage."},
        {"norwegian": "å overdrive", "english_meanings": "to exaggerate", "past": "overdrev", "past_participle": "overdrevet", "mnemonic": "Blow things out of proportion."},
        {"norwegian": "å overfalle", "english_meanings": "to attack", "past": "overfalt", "past_participle": "overfalt", "mnemonic": "Strike suddenly."},
        {"norwegian": "å overholde", "english_meanings": "to comply with", "past": "overholdt", "past_participle": "overholdt", "mnemonic": "Follow the rules."},
        {"norwegian": "å overlate", "english_meanings": "to entrust", "past": "overlatt", "past_participle": "overlatt", "mnemonic": "Hand over responsibility."},
        {"norwegian": "å overskride", "english_meanings": "to exceed", "past": "overskredet", "past_participle": "overskredet", "mnemonic": "Go beyond the limit."},
        {"norwegian": "å overta", "english_meanings": "to take over", "past": "overtok", "past_participle": "overtatt", "mnemonic": "Assume control."},
        {"norwegian": "å planlegge", "english_meanings": "to plan", "past": "planla", "past_participle": "planlagt", "mnemonic": "Devise a strategy."},
        {"norwegian": "å pådra", "english_meanings": "to incur", "past": "pådrog", "past_participle": "pådratt", "mnemonic": "Bring upon oneself."},
        {"norwegian": "å pågripe", "english_meanings": "to seize", "past": "pågrep", "past_participle": "pågrepet", "mnemonic": "Grab quickly."},
        {"norwegian": "å pågå", "english_meanings": "to be underway", "past": "pågikk", "past_participle": "pågått", "mnemonic": "Continue without stopping."},
        {"norwegian": "å pålegge", "english_meanings": "to impose", "past": "påla", "past_participle": "pålagt", "mnemonic": "Enforce a rule."},
        {"norwegian": "å påta", "english_meanings": "to undertake", "past": "påtok", "past_participle": "påtatt", "mnemonic": "Take on a responsibility."},
        {"norwegian": "å redegjøre", "english_meanings": "to explain", "past": "redegjorde", "past_participle": "redegjort", "mnemonic": "Lay out the details."},
        {"norwegian": "å rekke", "english_meanings": "to reach", "past": "rakte", "past_participle": "rakt", "mnemonic": "Extend to grab."},
        {"norwegian": "å renne", "english_meanings": "to run (liquid)", "past": "rant", "past_participle": "rent", "mnemonic": "Flow like a river."},
        {"norwegian": "å rive", "english_meanings": "to tear", "past": "rev", "past_participle": "revet", "mnemonic": "Rip apart."},
        {"norwegian": "å ryke", "english_meanings": "to combust", "past": "røket", "past_participle": "røket", "mnemonic": "Burn rapidly."},
        {"norwegian": "å se", "english_meanings": "to see", "past": "så", "past_participle": "sett", "mnemonic": "Perceive visually."},
        {"norwegian": "å selge", "english_meanings": "to sell", "past": "solgte", "past_participle": "solgt", "mnemonic": "Exchange for money."},
        {"norwegian": "å sette", "english_meanings": "to set", "past": "satte", "past_participle": "satt", "mnemonic": "Place in position."},
        {"norwegian": "å si", "english_meanings": "to say", "past": "sa", "past_participle": "sagt", "mnemonic": "Speak out loud."},
        {"norwegian": "å sige", "english_meanings": "to utter", "past": "seg", "past_participle": "seget", "mnemonic": "Express softly."},
        {"norwegian": "å sitte", "english_meanings": "to sit", "past": "satt", "past_participle": "sittet", "mnemonic": "Remain seated."},
        {"norwegian": "å skjelve", "english_meanings": "to tremble", "past": "skalv", "past_participle": "skjelvet", "mnemonic": "Shake with fear."},
        {"norwegian": "å skjære", "english_meanings": "to cut", "past": "skar", "past_participle": "skåret", "mnemonic": "Slice sharply."},
        {"norwegian": "å skli", "english_meanings": "to slip", "past": "sklidde", "past_participle": "sklidd", "mnemonic": "Lose your footing."},
        {"norwegian": "å skrike", "english_meanings": "to scream", "past": "skrek", "past_participle": "skreket", "mnemonic": "Scream loudly."},
        {"norwegian": "å skrive", "english_meanings": "to write", "past": "skrev", "past_participle": "skrevet", "mnemonic": "Put pen to paper."},
        {"norwegian": "å skryte", "english_meanings": "to boast", "past": "skrytte", "past_participle": "skrytt", "mnemonic": "Brag about achievements."},
        {"norwegian": "å skulle", "english_meanings": "to be supposed to", "past": "skullet", "past_participle": "skullet", "mnemonic": "Express obligation."},
        {"norwegian": "å skyldes", "english_meanings": "to be due to", "past": "skyldtes", "past_participle": "skyldes", "mnemonic": "Be caused by."},
        {"norwegian": "å skyte", "english_meanings": "to shoot", "past": "skjøt", "past_participle": "skutt", "mnemonic": "Fire a weapon."},
        {"norwegian": "å skyve", "english_meanings": "to push", "past": "skjøv", "past_participle": "skyvd", "mnemonic": "Shove forward."},
        {"norwegian": "å slenge", "english_meanings": "to sling / throw", "past": "slang", "past_participle": "slengt", "mnemonic": "Throw carelessly."},
        {"norwegian": "å slippe", "english_meanings": "to release", "past": "slapp", "past_participle": "sluppet", "mnemonic": "Let go gently."},
        {"norwegian": "å slite", "english_meanings": "to wear", "past": "slet", "past_participle": "slitt", "mnemonic": "Wear down gradually."},
        {"norwegian": "å slå", "english_meanings": "to hit", "past": "slo", "past_participle": "slått", "mnemonic": "Strike with force."},
        {"norwegian": "å slåss", "english_meanings": "to fight", "past": "sloss", "past_participle": "slåss", "mnemonic": "Engage in combat."},
        {"norwegian": "å smelle", "english_meanings": "to smash", "past": "smalt", "past_participle": "smelt", "mnemonic": "Collide loudly."},
        {"norwegian": "å smøre", "english_meanings": "to grease", "past": "smurte", "past_participle": "smurt", "mnemonic": "Apply oil smoothly."},
        {"norwegian": "å snike", "english_meanings": "to sneak", "past": "snek", "past_participle": "sneket", "mnemonic": "Move stealthily."},
        {"norwegian": "å sove", "english_meanings": "to sleep", "past": "sov", "past_participle": "sovet", "mnemonic": "Rest soundly."},
        {"norwegian": "å sprekke", "english_meanings": "to burst", "past": "sprakk", "past_participle": "sprukket", "mnemonic": "Explode suddenly."},
        {"norwegian": "å sprette", "english_meanings": "to bounce", "past": "spratt", "past_participle": "sprettet", "mnemonic": "Bounce energetically."},
        {"norwegian": "å springe", "english_meanings": "to run", "past": "sprang", "past_participle": "sprunget", "mnemonic": "Run swiftly."},
        {"norwegian": "å spørre", "english_meanings": "to ask", "past": "spurte", "past_participle": "spurt", "mnemonic": "Pose a question."},
        {"norwegian": "å stige", "english_meanings": "to ascend", "past": "steg", "past_participle": "steget", "mnemonic": "Climb upward."},
        {"norwegian": "å stikke", "english_meanings": "to sting", "past": "stakk", "past_participle": "stukket", "mnemonic": "Give a sharp poke."},
        {"norwegian": "å stjele", "english_meanings": "to steal", "past": "stjal", "past_participle": "stjålet", "mnemonic": "Take without permission."},
        {"norwegian": "å strekke", "english_meanings": "to stretch", "past": "strakk", "past_participle": "strukket", "mnemonic": "Extend your body."},
        {"norwegian": "å stride", "english_meanings": "to struggle", "past": "stridde", "past_participle": "stridd", "mnemonic": "Engage in a fight."},
        {"norwegian": "å stryke", "english_meanings": "to iron / strike", "past": "strøk", "past_participle": "strøket", "mnemonic": "Smooth out wrinkles."},
        {"norwegian": "å stå", "english_meanings": "to stand", "past": "sto", "past_participle": "stått", "mnemonic": "Remain upright."},
        {"norwegian": "å svi", "english_meanings": "to burn (singe)", "past": "svidde", "past_participle": "svidd", "mnemonic": "Feel a slight burn."},
        {"norwegian": "å svike", "english_meanings": "to betray", "past": "sveket", "past_participle": "sveket", "mnemonic": "Betray trust."},
        {"norwegian": "å synes", "english_meanings": "to seem", "past": "syntes", "past_participle": "syntes", "mnemonic": "Appear in a certain way."},
        {"norwegian": "å synge", "english_meanings": "to sing", "past": "sang", "past_participle": "sunget", "mnemonic": "Produce musical sounds."},
        {"norwegian": "å synke", "english_meanings": "to sink", "past": "sank", "past_participle": "sunket", "mnemonic": "Descend in water."},
        {"norwegian": "å ta", "english_meanings": "to take", "past": "tok", "past_participle": "tatt", "mnemonic": "Grab hold of something."},
        {"norwegian": "å tigge", "english_meanings": "to beg", "past": "tigga", "past_participle": "tigget", "mnemonic": "Implore humbly."},
        {"norwegian": "å tilbakelegge", "english_meanings": "to set aside", "past": "tilbakela", "past_participle": "tilbakelagt", "mnemonic": "Put away for later."},
        {"norwegian": "å tilbringe", "english_meanings": "to spend (time)", "past": "tilbragte", "past_participle": "tilbrakt", "mnemonic": "Spend quality time."},
        {"norwegian": "å tilby", "english_meanings": "to offer", "past": "tilbød", "past_participle": "tilbudt", "mnemonic": "Extend an offer."},
        {"norwegian": "å tilgi", "english_meanings": "to forgive", "past": "tilga", "past_participle": "tilgitt", "mnemonic": "Let go of resentment."},
        {"norwegian": "å tillate", "english_meanings": "to allow", "past": "tillot", "past_participle": "tillatt", "mnemonic": "Permit an action."},
        {"norwegian": "å tilsette", "english_meanings": "to add", "past": "tilsatte", "past_participle": "tilsatt", "mnemonic": "Mix in extra ingredients."},
        {"norwegian": "å tilsi", "english_meanings": "to imply", "past": "tilsa", "past_participle": "tilsagt", "mnemonic": "Suggest indirectly."},
        {"norwegian": "å tore", "english_meanings": "to dare", "past": "tørte", "past_participle": "tort", "mnemonic": "Have the courage."},
        {"norwegian": "å tre", "english_meanings": "to touch", "past": "tredde", "past_participle": "trådt", "mnemonic": "Lightly make contact."},
        {"norwegian": "å treffe", "english_meanings": "to hit / meet", "past": "traff", "past_participle": "truffet", "mnemonic": "Encounter unexpectedly."},
        {"norwegian": "å trekke", "english_meanings": "to pull", "past": "trakk", "past_participle": "trukket", "mnemonic": "Draw something nearer."},
        {"norwegian": "å trives", "english_meanings": "to thrive", "past": "trivdes", "past_participle": "trivdes", "mnemonic": "Do well in an environment."},
        {"norwegian": "å trå", "english_meanings": "to tread", "past": "trådte", "past_participle": "trådd", "mnemonic": "Step carefully."},
        {"norwegian": "å tviholde", "english_meanings": "to oppose", "past": "tviholdt", "past_participle": "tviholdt", "mnemonic": "Resist forcefully."},
        {"norwegian": "å tvinge", "english_meanings": "to force", "past": "tvang", "past_participle": "tvunget", "mnemonic": "Impose with strength."},
        {"norwegian": "å tørre", "english_meanings": "to dare", "past": "tørte", "past_participle": "tort", "mnemonic": "Challenge yourself."},
        {"norwegian": "å underskrive", "english_meanings": "to sign", "past": "underskrev", "past_participle": "underskrevet", "mnemonic": "Put your signature on it."},
        {"norwegian": "å unngå", "english_meanings": "to avoid", "past": "unngikk", "past_participle": "unngått", "mnemonic": "Steer clear of it."},
        {"norwegian": "å unnlate", "english_meanings": "to omit", "past": "unnlot", "past_participle": "unnlatt", "mnemonic": "Leave something out."},
        {"norwegian": "å utebli", "english_meanings": "to be absent", "past": "uteble", "past_participle": "uteblitt", "mnemonic": "Fail to appear."},
        {"norwegian": "å utgi", "english_meanings": "to publish", "past": "utgav", "past_participle": "utgitt", "mnemonic": "Release for public view."},
        {"norwegian": "å utgjøre", "english_meanings": "to constitute", "past": "utgjorde", "past_participle": "utgjort", "mnemonic": "Form the whole."},
        {"norwegian": "å utsette", "english_meanings": "to postpone", "past": "utsatte", "past_participle": "utsatt", "mnemonic": "Delay an action."},
        {"norwegian": "å vedta", "english_meanings": "to adopt / decide", "past": "vedtok", "past_participle": "vedtatt", "mnemonic": "Make a formal decision."},
        {"norwegian": "å velge", "english_meanings": "to choose", "past": "valgte", "past_participle": "valgt", "mnemonic": "Select from options."},
        {"norwegian": "å verdsette", "english_meanings": "to appreciate", "past": "verdsatte", "past_participle": "verdsatt", "mnemonic": "Value something highly."},
        {"norwegian": "å ville", "english_meanings": "to want", "past": "ville", "past_participle": "villet", "mnemonic": "Desire strongly."},
        {"norwegian": "å vinne", "english_meanings": "to win", "past": "vant", "past_participle": "vunnet", "mnemonic": "Achieve victory."},
        {"norwegian": "å vite", "english_meanings": "to know", "past": "visste", "past_participle": "visst", "mnemonic": "Have knowledge."},
        {"norwegian": "å voldta", "english_meanings": "to rape / violate", "past": "voldtok", "past_participle": "voldtatt", "mnemonic": "A very harsh action."},
        {"norwegian": "å vri", "english_meanings": "to twist", "past": "vridde", "past_participle": "vridd", "mnemonic": "Turn forcefully."},
        {"norwegian": "å være", "english_meanings": "to be", "past": "var", "past_participle": "vært", "mnemonic": "Simply exist."},
        {"norwegian": "å ødelegge", "english_meanings": "to destroy", "past": "ødela", "past_participle": "ødelagt", "mnemonic": "Completely ruin something."}
    ]
    
    for v in verbs:
        verb = Verb(
            norwegian=v["norwegian"],
            english_meanings=v["english_meanings"],
            past=v["past"],
            past_participle=v["past_participle"],
            mnemonic=v["mnemonic"]
        )
        db.session.add(verb)
        
    db.session.commit()
    print("Inserted {} verbs into the database.".format(len(verbs)))
