import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  const verbs = [
    {
      norwegian: "å angripe",
      englishMeanings: "to attack",
      past: "angrep",
      pastParticiple: "angrepet",
      mnemonic: "Sounds like 'attack'.",
    },
    {
      norwegian: "å anholde",
      englishMeanings: "to arrest",
      past: "anholdt",
      pastParticiple: "anholdt",
      mnemonic: "Think 'arrest hold'.",
    },
    {
      norwegian: "å ankomme",
      englishMeanings: "to arrive",
      past: "ankom",
      pastParticiple: "ankommet",
      mnemonic: "Arrived on time.",
    },
    {
      norwegian: "å anse",
      englishMeanings: "to consider",
      past: "anså",
      pastParticiple: "ansett",
      mnemonic: "Consider carefully.",
    },
    {
      norwegian: "å ansette",
      englishMeanings: "to hire",
      past: "ansatte",
      pastParticiple: "ansatt",
      mnemonic: "Hire someone for a job.",
    },
    {
      norwegian: "å anta",
      englishMeanings: "to assume",
      past: "antok",
      pastParticiple: "antatt",
      mnemonic: "Assume as true.",
    },
    {
      norwegian: "å avbryte",
      englishMeanings: "to interrupt",
      past: "avbrøt",
      pastParticiple: "avbrutt",
      mnemonic: "Interrupt the conversation.",
    },
    {
      norwegian: "å avgi",
      englishMeanings: "to emit / give off",
      past: "avga",
      pastParticiple: "avgitt",
      mnemonic: "Emit light or sound.",
    },
    {
      norwegian: "å avgjøre",
      englishMeanings: "to decide / determine",
      past: "avgjorde",
      pastParticiple: "avgjort",
      mnemonic: "Make a decision.",
    },
    {
      norwegian: "å avholde",
      englishMeanings: "to hold (a meeting)",
      past: "avholdt",
      pastParticiple: "avholdt",
      mnemonic: "Hold a session.",
    },
    {
      norwegian: "å avstå",
      englishMeanings: "to abstain",
      past: "avstod",
      pastParticiple: "avstått",
      mnemonic: "Refrain from something.",
    },
    {
      norwegian: "å avta",
      englishMeanings: "to decrease",
      past: "avtok",
      pastParticiple: "avtatt",
      mnemonic: "Decrease gradually.",
    },
    {
      norwegian: "å avvike",
      englishMeanings: "to deviate",
      past: "avvek",
      pastParticiple: "avveket",
      mnemonic: "Stray from the norm.",
    },
    {
      norwegian: "å be",
      englishMeanings: "to ask / pray",
      past: "ba",
      pastParticiple: "bedt",
      mnemonic: "Ask politely.",
    },
    {
      norwegian: "å begi",
      englishMeanings: "to undertake",
      past: "bega",
      pastParticiple: "begitt",
      mnemonic: "Undertake an action.",
    },
    {
      norwegian: "å bestå",
      englishMeanings: "to pass / consist of",
      past: "bestod",
      pastParticiple: "bestått",
      mnemonic: "Pass an exam.",
    },
    {
      norwegian: "å bidra",
      englishMeanings: "to contribute",
      past: "bidrog",
      pastParticiple: "bidratt",
      mnemonic: "Contribute to a cause.",
    },
    {
      norwegian: "å bifalle",
      englishMeanings: "to approve",
      past: "bifalt",
      pastParticiple: "bifalt",
      mnemonic: "Approve of something.",
    },
    {
      norwegian: "å binde",
      englishMeanings: "to bind",
      past: "bandt",
      pastParticiple: "bundet",
      mnemonic: "Bind tightly.",
    },
    {
      norwegian: "å bistå",
      englishMeanings: "to assist",
      past: "bisto",
      pastParticiple: "bistått",
      mnemonic: "Offer assistance.",
    },
    {
      norwegian: "å bite",
      englishMeanings: "to bite",
      past: "bet",
      pastParticiple: "bitt",
      mnemonic: "Bite with teeth.",
    },
    {
      norwegian: "å bli",
      englishMeanings: "to become",
      past: "blei",
      pastParticiple: "blitt",
      mnemonic: "Transform into something new.",
    },
    {
      norwegian: "å bosette",
      englishMeanings: "to settle",
      past: "bosatte",
      pastParticiple: "bosatt",
      mnemonic: "Settle in a place.",
    },
    {
      norwegian: "å brekke",
      englishMeanings: "to break (fracture)",
      past: "brakk",
      pastParticiple: "brukket",
      mnemonic: "Break suddenly.",
    },
    {
      norwegian: "å brenne",
      englishMeanings: "to burn",
      past: "brente",
      pastParticiple: "brent",
      mnemonic: "Burn intensely.",
    },
    {
      norwegian: "å bringe",
      englishMeanings: "to bring",
      past: "brakte",
      pastParticiple: "brakt",
      mnemonic: "Bring something along.",
    },
    {
      norwegian: "å bryte",
      englishMeanings: "to break",
      past: "brøt",
      pastParticiple: "brutt",
      mnemonic: "Break apart.",
    },
    {
      norwegian: "å burde",
      englishMeanings: "should / ought to",
      past: "burde",
      pastParticiple: "burdet",
      mnemonic: "Express obligation.",
    },
    {
      norwegian: "å by",
      englishMeanings: "to bid / offer",
      past: "bød",
      pastParticiple: "budt",
      mnemonic: "Place a bid.",
    },
    {
      norwegian: "å bære",
      englishMeanings: "to carry",
      past: "bar",
      pastParticiple: "båret",
      mnemonic: "Carry with effort.",
    },
    {
      norwegian: "å delta",
      englishMeanings: "to participate",
      past: "deltok",
      pastParticiple: "deltatt",
      mnemonic: "Join the activity.",
    },
    {
      norwegian: "å dra",
      englishMeanings: "to go / leave",
      past: "dro",
      pastParticiple: "dratt",
      mnemonic: "Depart quickly.",
    },
    {
      norwegian: "å drikke",
      englishMeanings: "to drink",
      past: "drakk",
      pastParticiple: "drukket",
      mnemonic: "Drink up.",
    },
    {
      norwegian: "å drive",
      englishMeanings: "to drive / operate",
      past: "drev",
      pastParticiple: "drevet",
      mnemonic: "Drive a vehicle.",
    },
    {
      norwegian: "å dø",
      englishMeanings: "to die",
      past: "døde",
      pastParticiple: "dødd",
      mnemonic: "Pass away.",
    },
    {
      norwegian: "å ete",
      englishMeanings: "to eat",
      past: "åt",
      pastParticiple: "ett",
      mnemonic: "Have a meal.",
    },
    {
      norwegian: "å etterkomme",
      englishMeanings: "to comply",
      past: "etterkom",
      pastParticiple: "etterkommet",
      mnemonic: "Follow orders.",
    },
    {
      norwegian: "å etterlate",
      englishMeanings: "to leave behind",
      past: "etterlot",
      pastParticiple: "etterlatt",
      mnemonic: "Leave a legacy.",
    },
    {
      norwegian: "å falle",
      englishMeanings: "to fall",
      past: "falt",
      pastParticiple: "falt",
      mnemonic: "Fall down.",
    },
    {
      norwegian: "å fastslå",
      englishMeanings: "to determine / establish",
      past: "fastslo",
      pastParticiple: "fastslått",
      mnemonic: "Establish a fact.",
    },
    {
      norwegian: "å ferdes",
      englishMeanings: "to travel",
      past: "ferdes",
      pastParticiple: "ferdes",
      mnemonic: "Travel around.",
    },
    {
      norwegian: "å finne",
      englishMeanings: "to find",
      past: "fant",
      pastParticiple: "funnet",
      mnemonic: "Discover something.",
    },
    {
      norwegian: "å finnes",
      englishMeanings: "to exist",
      past: "fantes",
      pastParticiple: "funnet",
      mnemonic: "Simply exist.",
    },
    {
      norwegian: "å fly",
      englishMeanings: "to fly",
      past: "fløy",
      pastParticiple: "flydd",
      mnemonic: "Soar in the sky.",
    },
    {
      norwegian: "å flyte",
      englishMeanings: "to float",
      past: "fløt",
      pastParticiple: "flytt",
      mnemonic: "Drift on water.",
    },
    {
      norwegian: "å forbryte",
      englishMeanings: "to commit a crime",
      past: "forbrøt",
      pastParticiple: "forbrutt",
      mnemonic: "Commit an offense.",
    },
    {
      norwegian: "å forby",
      englishMeanings: "to forbid",
      past: "forbød",
      pastParticiple: "forbudt",
      mnemonic: "Not allowed.",
    },
    {
      norwegian: "å fordra",
      englishMeanings: "to detest / abhor",
      past: "fordrog",
      pastParticiple: "fordratt",
      mnemonic: "Abhor strongly.",
    },
    {
      norwegian: "å foregå",
      englishMeanings: "to occur",
      past: "foregikk",
      pastParticiple: "foregått",
      mnemonic: "Happen as events.",
    },
    {
      norwegian: "å foreslå",
      englishMeanings: "to propose",
      past: "foreslo",
      pastParticiple: "foreslått",
      mnemonic: "Suggest an idea.",
    },
    {
      norwegian: "å foretrekke",
      englishMeanings: "to prefer",
      past: "foretrakk",
      pastParticiple: "foretrukket",
      mnemonic: "Favor one option.",
    },
    {
      norwegian: "å forfølge",
      englishMeanings: "to pursue",
      past: "forfulgte",
      pastParticiple: "forfulgt",
      mnemonic: "Chase after.",
    },
    {
      norwegian: "å forgå",
      englishMeanings: "to perish",
      past: "forgikk",
      pastParticiple: "forgått",
      mnemonic: "Pass away gradually.",
    },
    {
      norwegian: "å forholde",
      englishMeanings: "to relate / behave",
      past: "forholdt",
      pastParticiple: "forholdt",
      mnemonic: "Act in a certain way.",
    },
    {
      norwegian: "å forlate",
      englishMeanings: "to leave",
      past: "forlot",
      pastParticiple: "forlatt",
      mnemonic: "Depart from a place.",
    },
    {
      norwegian: "å forstå",
      englishMeanings: "to understand",
      past: "forsto",
      pastParticiple: "forstått",
      mnemonic: "Comprehend clearly.",
    },
    {
      norwegian: "å forsvinne",
      englishMeanings: "to vanish",
      past: "forsvant",
      pastParticiple: "forsvunnet",
      mnemonic: "Disappear suddenly.",
    },
    {
      norwegian: "å fortelle",
      englishMeanings: "to tell",
      past: "fortalte",
      pastParticiple: "fortalt",
      mnemonic: "Narrate a story.",
    },
    {
      norwegian: "å fortsette",
      englishMeanings: "to continue",
      past: "fortsatte",
      pastParticiple: "fortsatt",
      mnemonic: "Keep going.",
    },
    {
      norwegian: "å forutsette",
      englishMeanings: "to assume",
      past: "forutsatte",
      pastParticiple: "forutsatt",
      mnemonic: "Presume beforehand.",
    },
    {
      norwegian: "å frambringe",
      englishMeanings: "to produce",
      past: "frambrakte",
      pastParticiple: "frambrakt",
      mnemonic: "Bring forth something.",
    },
    {
      norwegian: "å frita",
      englishMeanings: "to excuse / exonerate",
      past: "fritok",
      pastParticiple: "fritatt",
      mnemonic: "Excuse from duty.",
    },
    {
      norwegian: "å fryse",
      englishMeanings: "to freeze",
      past: "frøs",
      pastParticiple: "frosset",
      mnemonic: "Turn to ice.",
    },
    {
      norwegian: "å få",
      englishMeanings: "to get / receive",
      past: "fikk",
      pastParticiple: "fått",
      mnemonic: "Obtain something.",
    },
    {
      norwegian: "å følge",
      englishMeanings: "to follow",
      past: "fulgte",
      pastParticiple: "fulgt",
      mnemonic: "Follow in footsteps.",
    },
    {
      norwegian: "å gi",
      englishMeanings: "to give",
      past: "gav",
      pastParticiple: "gitt",
      mnemonic: "Offer generously.",
    },
    {
      norwegian: "å gidde",
      englishMeanings: "to bother",
      past: "gadd",
      pastParticiple: "giddet",
      mnemonic: "Lack the energy to care.",
    },
    {
      norwegian: "å gjelde",
      englishMeanings: "to apply / concern",
      past: "gjaldt",
      pastParticiple: "gjeldt",
      mnemonic: "Apply to all.",
    },
    {
      norwegian: "å gjennomgå",
      englishMeanings: "to undergo / review",
      past: "gjennomgikk",
      pastParticiple: "gjennomgått",
      mnemonic: "Experience a process.",
    },
    {
      norwegian: "å gjenta",
      englishMeanings: "to repeat",
      past: "gjentok",
      pastParticiple: "gjentatt",
      mnemonic: "Do it again.",
    },
    {
      norwegian: "å gjenvinne",
      englishMeanings: "to regain",
      past: "gjenvant",
      pastParticiple: "gjenvunnet",
      mnemonic: "Win back possession.",
    },
    {
      norwegian: "å gjøre",
      englishMeanings: "to do",
      past: "gjorde",
      pastParticiple: "gjort",
      mnemonic: "Perform an action.",
    },
    {
      norwegian: "å gli",
      englishMeanings: "to slip",
      past: "gled",
      pastParticiple: "glidd",
      mnemonic: "Slide away.",
    },
    {
      norwegian: "å gni",
      englishMeanings: "to rub",
      past: "gnidde",
      pastParticiple: "gnidd",
      mnemonic: "Rub gently.",
    },
    {
      norwegian: "å godta",
      englishMeanings: "to accept",
      past: "godtok",
      pastParticiple: "godtatt",
      mnemonic: "Accept without hesitation.",
    },
    {
      norwegian: "å gravlegge",
      englishMeanings: "to bury",
      past: "gravla",
      pastParticiple: "gravlagt",
      mnemonic: "Lay to rest.",
    },
    {
      norwegian: "å gripe",
      englishMeanings: "to seize",
      past: "grep",
      pastParticiple: "grepet",
      mnemonic: "Grab quickly.",
    },
    {
      norwegian: "å grunnlegge",
      englishMeanings: "to establish",
      past: "grunnla",
      pastParticiple: "grunnlagt",
      mnemonic: "Lay a foundation.",
    },
    {
      norwegian: "å gråte",
      englishMeanings: "to cry",
      past: "gråt",
      pastParticiple: "grått",
      mnemonic: "Let the tears flow.",
    },
    {
      norwegian: "å gå",
      englishMeanings: "to go",
      past: "gikk",
      pastParticiple: "gått",
      mnemonic: "Move along.",
    },
    {
      norwegian: "å ha",
      englishMeanings: "to have",
      past: "hadde",
      pastParticiple: "hatt",
      mnemonic: "Possess something.",
    },
    {
      norwegian: "å henge",
      englishMeanings: "to hang",
      past: "hang",
      pastParticiple: "hengt",
      mnemonic: "Suspend from above.",
    },
    {
      norwegian: "å hete",
      englishMeanings: "to be called",
      past: "heta",
      pastParticiple: "hetet",
      mnemonic: "Be given a name.",
    },
    {
      norwegian: "å hjelpe",
      englishMeanings: "to help",
      past: "hjalp",
      pastParticiple: "hjulpet",
      mnemonic: "Offer assistance.",
    },
    {
      norwegian: "å holde",
      englishMeanings: "to hold",
      past: "holdt",
      pastParticiple: "holdt",
      mnemonic: "Grasp firmly.",
    },
    {
      norwegian: "å høres",
      englishMeanings: "to be heard",
      past: "hørtes",
      pastParticiple: "hørt",
      mnemonic: "Sound is perceived.",
    },
    {
      norwegian: "å innebære",
      englishMeanings: "to entail",
      past: "innebar",
      pastParticiple: "innebåret",
      mnemonic: "Imply a consequence.",
    },
    {
      norwegian: "å inneha",
      englishMeanings: "to possess",
      past: "innehadde",
      pastParticiple: "innehatt",
      mnemonic: "Hold ownership.",
    },
    {
      norwegian: "å inneholde",
      englishMeanings: "to contain",
      past: "inneholdt",
      pastParticiple: "inneholdt",
      mnemonic: "Enclose within.",
    },
    {
      norwegian: "å inngå",
      englishMeanings: "to enter into",
      past: "inngikk",
      pastParticiple: "inngått",
      mnemonic: "Enter an agreement.",
    },
    {
      norwegian: "å innse",
      englishMeanings: "to realize",
      past: "innså",
      pastParticiple: "innsett",
      mnemonic: "Comprehend suddenly.",
    },
    {
      norwegian: "å innsette",
      englishMeanings: "to insert / install",
      past: "innsatte",
      pastParticiple: "innsatt",
      mnemonic: "Place in position.",
    },
    {
      norwegian: "å inntre",
      englishMeanings: "to enter",
      past: "inntrådte",
      pastParticiple: "inntrådt",
      mnemonic: "Step inside.",
    },
    {
      norwegian: "å inntreffe",
      englishMeanings: "to occur",
      past: "inntraff",
      pastParticiple: "inntreffet",
      mnemonic: "Happen unexpectedly.",
    },
    {
      norwegian: "å iscenesette",
      englishMeanings: "to stage",
      past: "iscenesatte",
      pastParticiple: "iscenesatt",
      mnemonic: "Put on a performance.",
    },
    {
      norwegian: "å ivareta",
      englishMeanings: "to safeguard",
      past: "ivaretok",
      pastParticiple: "ivaretatt",
      mnemonic: "Take care of.",
    },
    {
      norwegian: "å kartlegge",
      englishMeanings: "to map out",
      past: "kartla",
      pastParticiple: "kartlagt",
      mnemonic: "Chart the details.",
    },
    {
      norwegian: "å klype",
      englishMeanings: "to pinch",
      past: "klypte",
      pastParticiple: "klypt",
      mnemonic: "Squeeze lightly.",
    },
    {
      norwegian: "å knekke",
      englishMeanings: "to crack",
      past: "knakk",
      pastParticiple: "knekket",
      mnemonic: "Break open.",
    },
    {
      norwegian: "å komme",
      englishMeanings: "to come",
      past: "kom",
      pastParticiple: "kommet",
      mnemonic: "Arrive at a place.",
    },
    {
      norwegian: "å krype",
      englishMeanings: "to crawl",
      past: "krøyp",
      pastParticiple: "krøpet",
      mnemonic: "Crawl slowly.",
    },
    {
      norwegian: "å kunne",
      englishMeanings: "to be able to",
      past: "kunne",
      pastParticiple: "kunnet",
      mnemonic: "Have the ability.",
    },
    {
      norwegian: "å la",
      englishMeanings: "to let",
      past: "lot",
      pastParticiple: "latt",
      mnemonic: "Allow to happen.",
    },
    {
      norwegian: "å late",
      englishMeanings: "to pretend",
      past: "lot",
      pastParticiple: "latt",
      mnemonic: "Feign an emotion.",
    },
    {
      norwegian: "å le",
      englishMeanings: "to laugh",
      past: "lo",
      pastParticiple: "ledd",
      mnemonic: "Laugh out loud.",
    },
    {
      norwegian: "å legge",
      englishMeanings: "to put / lay",
      past: "la",
      pastParticiple: "lagt",
      mnemonic: "Place something down.",
    },
    {
      norwegian: "å lete",
      englishMeanings: "to search",
      past: "lette",
      pastParticiple: "lett",
      mnemonic: "Look for something.",
    },
    {
      norwegian: "å lide",
      englishMeanings: "to suffer",
      past: "led",
      pastParticiple: "lidd",
      mnemonic: "Endure hardship.",
    },
    {
      norwegian: "å ligge",
      englishMeanings: "to lie (recline)",
      past: "lå",
      pastParticiple: "ligget",
      mnemonic: "Rest in bed.",
    },
    {
      norwegian: "å lyde",
      englishMeanings: "to sound",
      past: "lydde",
      pastParticiple: "lydt",
      mnemonic: "Produce a sound.",
    },
    {
      norwegian: "å lyge",
      englishMeanings: "to lie (deceive)",
      past: "løy",
      pastParticiple: "løyet",
      mnemonic: "Speak falsely.",
    },
    {
      norwegian: "å lykkes",
      englishMeanings: "to succeed",
      past: "lyktes",
      pastParticiple: "lyktes",
      mnemonic: "Achieve your goal.",
    },
    {
      norwegian: "å lyve",
      englishMeanings: "to lie (deceit)",
      past: "løy",
      pastParticiple: "løyet",
      mnemonic: "Tell an untruth.",
    },
    {
      norwegian: "å løpe",
      englishMeanings: "to run",
      past: "løp",
      pastParticiple: "løpt",
      mnemonic: "Run swiftly.",
    },
    {
      norwegian: "å løslate",
      englishMeanings: "to release",
      past: "løslot",
      pastParticiple: "løslatt",
      mnemonic: "Let go of restraint.",
    },
    {
      norwegian: "å minnes",
      englishMeanings: "to remember",
      past: "mintes",
      pastParticiple: "mintes",
      mnemonic: "Keep in mind.",
    },
    {
      norwegian: "å misforstå",
      englishMeanings: "to misunderstand",
      past: "misforsto",
      pastParticiple: "misforstått",
      mnemonic: "Get it wrong.",
    },
    {
      norwegian: "å motta",
      englishMeanings: "to receive",
      past: "mottok",
      pastParticiple: "mottatt",
      mnemonic: "Accept what is given.",
    },
    {
      norwegian: "å måtte",
      englishMeanings: "to have to",
      past: "måtte",
      pastParticiple: "måttet",
      mnemonic: "Need to do something.",
    },
    {
      norwegian: "å møtes",
      englishMeanings: "to meet",
      past: "møttes",
      pastParticiple: "møttes",
      mnemonic: "Come together.",
    },
    {
      norwegian: "å nedlegge",
      englishMeanings: "to abolish",
      past: "nedla",
      pastParticiple: "nedlagt",
      mnemonic: "Put an end to something.",
    },
    {
      norwegian: "å nedsette",
      englishMeanings: "to dismiss",
      past: "nedsatte",
      pastParticiple: "nedsatt",
      mnemonic: "Lower the status.",
    },
    {
      norwegian: "å nyse",
      englishMeanings: "to sneeze",
      past: "nyste",
      pastParticiple: "nyst",
      mnemonic: "Expel air suddenly.",
    },
    {
      norwegian: "å nyte",
      englishMeanings: "to enjoy",
      past: "nøt",
      pastParticiple: "nytt",
      mnemonic: "Savor the moment.",
    },
    {
      norwegian: "å omgå",
      englishMeanings: "to bypass / circumvent",
      past: "omgikk",
      pastParticiple: "omgått",
      mnemonic: "Go around obstacles.",
    },
    {
      norwegian: "å omgås",
      englishMeanings: "to socialize",
      past: "omgikkes",
      pastParticiple: "omgåttes",
      mnemonic: "Spend time with others.",
    },
    {
      norwegian: "å oppdra",
      englishMeanings: "to bring up / educate",
      past: "oppdro",
      pastParticiple: "oppdratt",
      mnemonic: "Raise a child.",
    },
    {
      norwegian: "å oppfinne",
      englishMeanings: "to invent",
      past: "oppfant",
      pastParticiple: "oppfunnet",
      mnemonic: "Create something new.",
    },
    {
      norwegian: "å oppgi",
      englishMeanings: "to give up",
      past: "oppgav",
      pastParticiple: "oppgitt",
      mnemonic: "Surrender reluctantly.",
    },
    {
      norwegian: "å oppholde",
      englishMeanings: "to stay / reside",
      past: "oppholdt",
      pastParticiple: "oppholdt",
      mnemonic: "Remain somewhere.",
    },
    {
      norwegian: "å opprettholde",
      englishMeanings: "to maintain",
      past: "opprettholdt",
      pastParticiple: "opprettholdt",
      mnemonic: "Keep things in order.",
    },
    {
      norwegian: "å oppstå",
      englishMeanings: "to arise",
      past: "oppsto",
      pastParticiple: "oppstått",
      mnemonic: "Emerge unexpectedly.",
    },
    {
      norwegian: "å oppta",
      englishMeanings: "to occupy",
      past: "opptok",
      pastParticiple: "opptatt",
      mnemonic: "Take up space.",
    },
    {
      norwegian: "å opptre",
      englishMeanings: "to perform",
      past: "opptrådte",
      pastParticiple: "opptrådt",
      mnemonic: "Take the stage.",
    },
    {
      norwegian: "å overdrive",
      englishMeanings: "to exaggerate",
      past: "overdrev",
      pastParticiple: "overdrevet",
      mnemonic: "Blow things out of proportion.",
    },
    {
      norwegian: "å overfalle",
      englishMeanings: "to attack",
      past: "overfalt",
      pastParticiple: "overfalt",
      mnemonic: "Strike suddenly.",
    },
    {
      norwegian: "å overholde",
      englishMeanings: "to comply with",
      past: "overholdt",
      pastParticiple: "overholdt",
      mnemonic: "Follow the rules.",
    },
    {
      norwegian: "å overlate",
      englishMeanings: "to entrust",
      past: "overlatt",
      pastParticiple: "overlatt",
      mnemonic: "Hand over responsibility.",
    },
    {
      norwegian: "å overskride",
      englishMeanings: "to exceed",
      past: "overskredet",
      pastParticiple: "overskredet",
      mnemonic: "Go beyond the limit.",
    },
    {
      norwegian: "å overta",
      englishMeanings: "to take over",
      past: "overtok",
      pastParticiple: "overtatt",
      mnemonic: "Assume control.",
    },
    {
      norwegian: "å planlegge",
      englishMeanings: "to plan",
      past: "planla",
      pastParticiple: "planlagt",
      mnemonic: "Devise a strategy.",
    },
    {
      norwegian: "å pådra",
      englishMeanings: "to incur",
      past: "pådrog",
      pastParticiple: "pådratt",
      mnemonic: "Bring upon oneself.",
    },
    {
      norwegian: "å pågripe",
      englishMeanings: "to seize",
      past: "pågrep",
      pastParticiple: "pågrepet",
      mnemonic: "Grab quickly.",
    },
    {
      norwegian: "å pågå",
      englishMeanings: "to be underway",
      past: "pågikk",
      pastParticiple: "pågått",
      mnemonic: "Continue without stopping.",
    },
    {
      norwegian: "å pålegge",
      englishMeanings: "to impose",
      past: "påla",
      pastParticiple: "pålagt",
      mnemonic: "Enforce a rule.",
    },
    {
      norwegian: "å påta",
      englishMeanings: "to undertake",
      past: "påtok",
      pastParticiple: "påtatt",
      mnemonic: "Take on a responsibility.",
    },
    {
      norwegian: "å redegjøre",
      englishMeanings: "to explain",
      past: "redegjorde",
      pastParticiple: "redegjort",
      mnemonic: "Lay out the details.",
    },
    {
      norwegian: "å rekke",
      englishMeanings: "to reach",
      past: "rakte",
      pastParticiple: "rakt",
      mnemonic: "Extend to grab.",
    },
    {
      norwegian: "å renne",
      englishMeanings: "to run (liquid)",
      past: "rant",
      pastParticiple: "rent",
      mnemonic: "Flow like a river.",
    },
    {
      norwegian: "å rive",
      englishMeanings: "to tear",
      past: "rev",
      pastParticiple: "revet",
      mnemonic: "Rip apart.",
    },
    {
      norwegian: "å ryke",
      englishMeanings: "to combust",
      past: "røket",
      pastParticiple: "røket",
      mnemonic: "Burn rapidly.",
    },
    {
      norwegian: "å se",
      englishMeanings: "to see",
      past: "så",
      pastParticiple: "sett",
      mnemonic: "Perceive visually.",
    },
    {
      norwegian: "å selge",
      englishMeanings: "to sell",
      past: "solgte",
      pastParticiple: "solgt",
      mnemonic: "Exchange for money.",
    },
    {
      norwegian: "å sette",
      englishMeanings: "to set",
      past: "satte",
      pastParticiple: "satt",
      mnemonic: "Place in position.",
    },
    {
      norwegian: "å si",
      englishMeanings: "to say",
      past: "sa",
      pastParticiple: "sagt",
      mnemonic: "Speak out loud.",
    },
    {
      norwegian: "å sige",
      englishMeanings: "to utter",
      past: "seg",
      pastParticiple: "seget",
      mnemonic: "Express softly.",
    },
    {
      norwegian: "å sitte",
      englishMeanings: "to sit",
      past: "satt",
      pastParticiple: "sittet",
      mnemonic: "Remain seated.",
    },
    {
      norwegian: "å skjelve",
      englishMeanings: "to tremble",
      past: "skalv",
      pastParticiple: "skjelvet",
      mnemonic: "Shake with fear.",
    },
    {
      norwegian: "å skjære",
      englishMeanings: "to cut",
      past: "skar",
      pastParticiple: "skåret",
      mnemonic: "Slice sharply.",
    },
    {
      norwegian: "å skli",
      englishMeanings: "to slip",
      past: "skled",
      pastParticiple: "sklidd",
      mnemonic: "Lose your footing.",
    },
    {
      norwegian: "å skrike",
      englishMeanings: "to scream",
      past: "skrek",
      pastParticiple: "skreket",
      mnemonic: "Scream loudly.",
    },
    {
      norwegian: "å skrive",
      englishMeanings: "to write",
      past: "skrev",
      pastParticiple: "skrevet",
      mnemonic: "Put pen to paper.",
    },
    {
      norwegian: "å skryte",
      englishMeanings: "to boast",
      past: "skrøt",
      pastParticiple: "skrytt",
      mnemonic: "Brag about achievements.",
    },
    {
      norwegian: "å skulle",
      englishMeanings: "to be supposed to",
      past: "skulle",
      pastParticiple: "skullet",
      mnemonic: "Express obligation.",
    },
    {
      norwegian: "å skyldes",
      englishMeanings: "to be due to",
      past: "skyldtes",
      pastParticiple: "skyldes",
      mnemonic: "Be caused by.",
    },
    {
      norwegian: "å skyte",
      englishMeanings: "to shoot",
      past: "skjøt",
      pastParticiple: "skutt",
      mnemonic: "Fire a weapon.",
    },
    {
      norwegian: "å skyve",
      englishMeanings: "to push",
      past: "skjøv",
      pastParticiple: "skyvd",
      mnemonic: "Shove forward.",
    },
    {
      norwegian: "å slenge",
      englishMeanings: "to sling / throw",
      past: "slang",
      pastParticiple: "slengt",
      mnemonic: "Throw carelessly.",
    },
    {
      norwegian: "å slippe",
      englishMeanings: "to release",
      past: "slapp",
      pastParticiple: "sluppet",
      mnemonic: "Let go gently.",
    },
    {
      norwegian: "å slite",
      englishMeanings: "to wear",
      past: "slet",
      pastParticiple: "slitt",
      mnemonic: "Wear down gradually.",
    },
    {
      norwegian: "å slå",
      englishMeanings: "to hit",
      past: "slo",
      pastParticiple: "slått",
      mnemonic: "Strike with force.",
    },
    {
      norwegian: "å slåss",
      englishMeanings: "to fight",
      past: "sloss",
      pastParticiple: "slåss",
      mnemonic: "Engage in combat.",
    },
    {
      norwegian: "å smelle",
      englishMeanings: "to smash",
      past: "smalt",
      pastParticiple: "smelt",
      mnemonic: "Collide loudly.",
    },
    {
      norwegian: "å smøre",
      englishMeanings: "to grease",
      past: "smurte",
      pastParticiple: "smurt",
      mnemonic: "Apply oil smoothly.",
    },
    {
      norwegian: "å snike",
      englishMeanings: "to sneak",
      past: "snek",
      pastParticiple: "sneket",
      mnemonic: "Move stealthily.",
    },
    {
      norwegian: "å sove",
      englishMeanings: "to sleep",
      past: "sov",
      pastParticiple: "sovet",
      mnemonic: "Rest soundly.",
    },
    {
      norwegian: "å sprekke",
      englishMeanings: "to burst",
      past: "sprakk",
      pastParticiple: "sprukket",
      mnemonic: "Explode suddenly.",
    },
    {
      norwegian: "å sprette",
      englishMeanings: "to bounce",
      past: "spratt",
      pastParticiple: "sprettet",
      mnemonic: "Bounce energetically.",
    },
    {
      norwegian: "å springe",
      englishMeanings: "to run",
      past: "sprang",
      pastParticiple: "sprunget",
      mnemonic: "Run swiftly.",
    },
    {
      norwegian: "å spørre",
      englishMeanings: "to ask",
      past: "spurte",
      pastParticiple: "spurt",
      mnemonic: "Pose a question.",
    },
    {
      norwegian: "å stige",
      englishMeanings: "to ascend",
      past: "steg",
      pastParticiple: "steget",
      mnemonic: "Climb upward.",
    },
    {
      norwegian: "å stikke",
      englishMeanings: "to sting",
      past: "stakk",
      pastParticiple: "stukket",
      mnemonic: "Give a sharp poke.",
    },
    {
      norwegian: "å stjele",
      englishMeanings: "to steal",
      past: "stjal",
      pastParticiple: "stjålet",
      mnemonic: "Take without permission.",
    },
    {
      norwegian: "å strekke",
      englishMeanings: "to stretch",
      past: "strakk",
      pastParticiple: "strukket",
      mnemonic: "Extend your body.",
    },
    {
      norwegian: "å stride",
      englishMeanings: "to struggle",
      past: "stred",
      pastParticiple: "stridd",
      mnemonic: "Engage in a fight.",
    },
    {
      norwegian: "å stryke",
      englishMeanings: "to iron / strike",
      past: "strøk",
      pastParticiple: "strøket",
      mnemonic: "Smooth out wrinkles.",
    },
    {
      norwegian: "å stå",
      englishMeanings: "to stand",
      past: "sto",
      pastParticiple: "stått",
      mnemonic: "Remain upright.",
    },
    {
      norwegian: "å svi",
      englishMeanings: "to burn (singe)",
      past: "svidde",
      pastParticiple: "svidd",
      mnemonic: "Feel a slight burn.",
    },
    {
      norwegian: "å svike",
      englishMeanings: "to betray",
      past: "svek",
      pastParticiple: "sveket",
      mnemonic: "Betray trust.",
    },
    {
      norwegian: "å synes",
      englishMeanings: "to seem",
      past: "syntes",
      pastParticiple: "syntes",
      mnemonic: "Appear in a certain way.",
    },
    {
      norwegian: "å synge",
      englishMeanings: "to sing",
      past: "sang",
      pastParticiple: "sunget",
      mnemonic: "Produce musical sounds.",
    },
    {
      norwegian: "å synke",
      englishMeanings: "to sink",
      past: "sank",
      pastParticiple: "sunket",
      mnemonic: "Descend in water.",
    },
    {
      norwegian: "å ta",
      englishMeanings: "to take",
      past: "tok",
      pastParticiple: "tatt",
      mnemonic: "Grab hold of something.",
    },
    {
      norwegian: "å tigge",
      englishMeanings: "to beg",
      past: "tigget",
      pastParticiple: "tigget",
      mnemonic: "Implore humbly.",
    },
    {
      norwegian: "å tilbakelegge",
      englishMeanings: "to set aside",
      past: "tilbakela",
      pastParticiple: "tilbakelagt",
      mnemonic: "Put away for later.",
    },
    {
      norwegian: "å tilbringe",
      englishMeanings: "to spend (time)",
      past: "tilbrakte",
      pastParticiple: "tilbrakt",
      mnemonic: "Spend quality time.",
    },
    {
      norwegian: "å tilby",
      englishMeanings: "to offer",
      past: "tilbød",
      pastParticiple: "tilbudt",
      mnemonic: "Extend an offer.",
    },
    {
      norwegian: "å tilgi",
      englishMeanings: "to forgive",
      past: "tilga",
      pastParticiple: "tilgitt",
      mnemonic: "Let go of resentment.",
    },
    {
      norwegian: "å tillate",
      englishMeanings: "to allow",
      past: "tillot",
      pastParticiple: "tillatt",
      mnemonic: "Permit an action.",
    },
    {
      norwegian: "å tilsette",
      englishMeanings: "to add",
      past: "tilsatte",
      pastParticiple: "tilsatt",
      mnemonic: "Mix in extra ingredients.",
    },
    {
      norwegian: "å tilsi",
      englishMeanings: "to imply",
      past: "tilsa",
      pastParticiple: "tilsagt",
      mnemonic: "Suggest indirectly.",
    },
    {
      norwegian: "å tore",
      englishMeanings: "to dare",
      past: "torde",
      pastParticiple: "tort",
      mnemonic: "Have the courage.",
    },
    {
      norwegian: "å tre",
      englishMeanings: "to step/enter",
      past: "trådte",
      pastParticiple: "trådt",
      mnemonic: "Step into a room.",
    },
    {
      norwegian: "å treffe",
      englishMeanings: "to hit / meet",
      past: "traff",
      pastParticiple: "truffet",
      mnemonic: "Encounter unexpectedly.",
    },
    {
      norwegian: "å trekke",
      englishMeanings: "to pull",
      past: "trakk",
      pastParticiple: "trukket",
      mnemonic: "Draw something nearer.",
    },
    {
      norwegian: "å trives",
      englishMeanings: "to thrive",
      past: "trivdes",
      pastParticiple: "trivdes",
      mnemonic: "Do well in an environment.",
    },
    {
      norwegian: "å trå",
      englishMeanings: "to tread",
      past: "trådte",
      pastParticiple: "trådd",
      mnemonic: "Step carefully.",
    },
    {
      norwegian: "å tviholde",
      englishMeanings: "to oppose",
      past: "tviholdt",
      pastParticiple: "tviholdt",
      mnemonic: "Resist forcefully.",
    },
    {
      norwegian: "å tvinge",
      englishMeanings: "to force",
      past: "tvang",
      pastParticiple: "tvunget",
      mnemonic: "Impose with strength.",
    },
    {
      norwegian: "å tørre",
      englishMeanings: "to dare",
      past: "torde",
      pastParticiple: "tort",
      mnemonic: "Challenge yourself.",
    },
    {
      norwegian: "å underskrive",
      englishMeanings: "to sign",
      past: "underskrev",
      pastParticiple: "underskrevet",
      mnemonic: "Put your signature on it.",
    },
    {
      norwegian: "å unngå",
      englishMeanings: "to avoid",
      past: "unngikk",
      pastParticiple: "unngått",
      mnemonic: "Steer clear of it.",
    },
    {
      norwegian: "å unnlate",
      englishMeanings: "to omit",
      past: "unnlot",
      pastParticiple: "unnlatt",
      mnemonic: "Leave something out.",
    },
    {
      norwegian: "å utebli",
      englishMeanings: "to be absent",
      past: "uteble",
      pastParticiple: "uteblitt",
      mnemonic: "Fail to appear.",
    },
    {
      norwegian: "å utgi",
      englishMeanings: "to publish",
      past: "utgav",
      pastParticiple: "utgitt",
      mnemonic: "Release for public view.",
    },
    {
      norwegian: "å utgjøre",
      englishMeanings: "to constitute",
      past: "utgjorde",
      pastParticiple: "utgjort",
      mnemonic: "Form the whole.",
    },
    {
      norwegian: "å utsette",
      englishMeanings: "to postpone",
      past: "utsatte",
      pastParticiple: "utsatt",
      mnemonic: "Delay an action.",
    },
    {
      norwegian: "å vedta",
      englishMeanings: "to adopt / decide",
      past: "vedtok",
      pastParticiple: "vedtatt",
      mnemonic: "Make a formal decision.",
    },
    {
      norwegian: "å velge",
      englishMeanings: "to choose",
      past: "valgte",
      pastParticiple: "valgt",
      mnemonic: "Select from options.",
    },
    {
      norwegian: "å verdsette",
      englishMeanings: "to appreciate",
      past: "verdsatte",
      pastParticiple: "verdsatt",
      mnemonic: "Value something highly.",
    },
    {
      norwegian: "å ville",
      englishMeanings: "to want",
      past: "ville",
      pastParticiple: "villet",
      mnemonic: "Desire strongly.",
    },
    {
      norwegian: "å vinne",
      englishMeanings: "to win",
      past: "vant",
      pastParticiple: "vunnet",
      mnemonic: "Achieve victory.",
    },
    {
      norwegian: "å vite",
      englishMeanings: "to know",
      past: "visste",
      pastParticiple: "visst",
      mnemonic: "Have knowledge.",
    },
    {
      norwegian: "å voldta",
      englishMeanings: "to rape / violate",
      past: "voldtok",
      pastParticiple: "voldtatt",
      mnemonic: "A very harsh action.",
    },
    {
      norwegian: "å vri",
      englishMeanings: "to twist",
      past: "vred",
      pastParticiple: "vridd",
      mnemonic: "Turn forcefully.",
    },
    {
      norwegian: "å være",
      englishMeanings: "to be",
      past: "var",
      pastParticiple: "vært",
      mnemonic: "Simply exist.",
    },
    {
      norwegian: "å ødelegge",
      englishMeanings: "to destroy",
      past: "ødela",
      pastParticiple: "ødelagt",
      mnemonic: "Completely ruin something.",
    }
  ]

  console.log(`Start seeding verbs...`)
  
  for (const verb of verbs) {
    const createdVerb = await prisma.verb.upsert({
      where: { norwegian: verb.norwegian },
      update: {
        englishMeanings: verb.englishMeanings,
        past: verb.past,
        pastParticiple: verb.pastParticiple,
        mnemonic: verb.mnemonic
      },
      create: {
        norwegian: verb.norwegian,
        englishMeanings: verb.englishMeanings,
        past: verb.past,
        pastParticiple: verb.pastParticiple,
        mnemonic: verb.mnemonic
      }
    })
    console.log(`Created verb: ${createdVerb.norwegian}`)
  }
  
  console.log(`Seeding finished.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })    