"""Migrate from SQLite to PostgreSQL

Revision ID: 3078bcbc9f98
Revises: 
Create Date: 2025-02-07 13:20:20.450044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3078bcbc9f98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norwegian', sa.String(length=80), nullable=False),
    sa.Column('english_meanings', sa.String(length=200), nullable=True),
    sa.Column('past', sa.String(length=80), nullable=True),
    sa.Column('past_participle', sa.String(length=80), nullable=True),
    sa.Column('mnemonic', sa.String(length=250), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('norwegian')
    )
    op.create_table('user_verb_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verb_id', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('correct_attempts', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verb_id'], ['verb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_verb_progress')
    op.drop_table('verb')
    op.drop_table('user')
    # ### end Alembic commands ###
